let First = document.getElementById('1')
let Second = document.getElementById('2')
let Third = document.getElementById('3')
let Fourth = document.getElementById('4')
let Fiveth = document.getElementById('5')
let Sixth = document.getElementById('6')
let Seventh = document.getElementById('7')
let Eighth = document.getElementById('8')
let Nineth = document.getElementById('9')
let Tenth = document.getElementById('10')

let H11 = document.getElementById('11')
let H12 = document.getElementById('12')
let H13 = document.getElementById('13')
let H14 = document.getElementById('14')

let H21 = document.getElementById('21')
let H22 = document.getElementById('22')
let H23 = document.getElementById('23')
let H24 = document.getElementById('24')

let H31 = document.getElementById('31')
let H32 = document.getElementById('32')
let H33 = document.getElementById('33')
let H34 = document.getElementById('34')

let H41 = document.getElementById('41')
let H42 = document.getElementById('42')
let H43 = document.getElementById('43')
let H44 = document.getElementById('44')

let H51 = document.getElementById('51')
let H52 = document.getElementById('52')
let H53 = document.getElementById('53')
let H54 = document.getElementById('54')

let H61 = document.getElementById('61')
let H62 = document.getElementById('62')
let H63 = document.getElementById('63')
let H64 = document.getElementById('64')

let H71 = document.getElementById('71')
let H72 = document.getElementById('72')
let H73 = document.getElementById('73')
let H74 = document.getElementById('74')

let H81 = document.getElementById('81')
let H82 = document.getElementById('82')
let H83 = document.getElementById('83')
let H84 = document.getElementById('84')

let H91 = document.getElementById('91')
let H92 = document.getElementById('92')
let H93 = document.getElementById('93')
let H94 = document.getElementById('94')

let H101 = document.getElementById('101')
let H102 = document.getElementById('102')
let H103 = document.getElementById('103')
let H104 = document.getElementById('104')